### ISSUE TITLE
Multipart form format

### ISSUE THREAD

**Issue by kellansteele** [louisoutin/yolov5_torchserve#2]
Could you provide an example of how you convert your images to bytes and how you're formatting your POST requests (specifically how to include the bytes)? As someone who's never seen any of this before, it would be really helpful! Thank you!

**Comment by louisoutin** [comment]
I do it like this:
from images files, I read the bytes and add each bytes array to a dict containing the batches for the network to predict, ex:

```
def get_predictions(raw_frames_path: List[Path],
                    batch_size: int
                    ):
    batch = {}
    cpt = 1
    predictions = []
    images_paths = [p.as_posix() for p in raw_frames_path]
    logging.warning(f"images_paths {str(images_paths)}")
    for frame in sorted(images_paths):
        key = "img" + str(cpt)
        cpt += 1
        batch[key] = open(frame, 'rb')
        if len(batch.keys()) >= batch_size:
            # call torchserve predictions
            predictions += _get_prediction(batch)
            batch = {}  # reset batch
            cpt = 1  # reset image idx
    if len(batch.keys()) > 0:
        predictions += _get_prediction(batch)
    return predictions
```

**Comment by kellansteele** [comment]
What do you mean by `List[Path]` ?

**Comment by louisoutin** [comment]
My function accepts a list of pathlib.Path objects. But you can do the same functions with strings instead, it will work fine
