### ISSUE TITLE
No response error

### ISSUE THREAD

**Issue by valerietram88** [louisoutin/yolov5_torchserve#4]
Thank you for your sharing.

But I get "No response" as result of request. I use CPU. May you have any idea? Thank you in advance!

![image](https://user-images.githubusercontent.com/68628367/110194959-0a586680-7e6e-11eb-841c-1046f1a26430.png)

**Comment by louisoutin** [comment]
Hello,

This repository is made for a config using GPU (the torchserve image to use i not the same (different tag)).
Please use this image instead: https://hub.docker.com/layers/pytorch/torchserve/0.3.0-cpu/images/sha256-09135470e8e5a97bbbb2c22027da5624c1bd944dd289eba63b1f7369ea42ace8?context=explore

PS: I don't have time to update the repository thoses last weeks to make things more flexible (option for cpu/gpu) and to try the latest torchserve version v0.3.

**Comment by valerietram88** [comment]
> Hello,
> 
> This repository is made for a config using GPU (the torchserve image to use i not the same (different tag)).
> Please use this image instead: https://hub.docker.com/layers/pytorch/torchserve/0.3.0-cpu/images/sha256-09135470e8e5a97bbbb2c22027da5624c1bd944dd289eba63b1f7369ea42ace8?context=explore
> 
> PS: I don't have time to update the repository thoses last weeks to make things more flexible (option for cpu/gpu) and to try the latest torchserve version v0.3.

Thank you for your answer. 
I try many times to make your code work correctly to get correct results but I cannot. 
+ Using dockerfile you give, I get the docker image but I don't know how to use the model to inference, how to pass the images ...
+ Not using dockerfile, I pass images by "curl" command in terminal or using API tester. It works but result of request is [ [] ]. 

May you tell me how to pass images to inference. Thank you in advance!

![image](https://user-images.githubusercontent.com/68628367/110877091-635f4900-830b-11eb-8eb1-7675a5f6b22e.png)

**Comment by louisoutin** [comment]
Your request is returning 200, it seems to be working. It's just that there is no predictions returned by the model.
Maybe your model is not correctly trained or the image you pass on your request contains no known class to detect.
